import type { IsDay, WeatherCode, WeatherGroup } from '@/types/weather'

export const WEATHER_CODE_MAP: Record<WeatherCode, string> = {
  0: 'Clear sky',
  1: 'Mainly clear',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Rime fog',
  51: 'Light drizzle',
  53: 'Moderate drizzle',
  55: 'Dense drizzle',
  61: 'Slight rain',
  63: 'Moderate rain',
  65: 'Heavy rain',
  71: 'Slight snow',
  73: 'Moderate snow',
  75: 'Heavy snow',
  77: 'Snow grains',
  80: 'Slight rain showers',
  81: 'Moderate rain showers',
  82: 'Violent rain showers',
  85: 'Slight snow showers',
  86: 'Heavy snow showers',
  95: 'Thunderstorm',
  96: 'Thunderstorm with slight hail',
  99: 'Thunderstorm with heavy hail',
}

export const WEATHER_ICON_MAP: Record<WeatherCode, Record<IsDay, string>> = {
  0:  { 1: 'clear-day',                    0: 'clear-night' },
  1:  { 1: 'clear-day',                    0: 'clear-night' },
  2:  { 1: 'partly-cloudy-day',            0: 'partly-cloudy-night' },
  3:  { 1: 'overcast-day',                 0: 'overcast-night' },
  45: { 1: 'fog-day',                      0: 'fog-night' },
  48: { 1: 'fog-day',                      0: 'fog-night' },
  51: { 1: 'partly-cloudy-day-drizzle',    0: 'partly-cloudy-night-drizzle' },
  53: { 1: 'partly-cloudy-day-drizzle',    0: 'partly-cloudy-night-drizzle' },
  55: { 1: 'drizzle',                      0: 'drizzle' },
  61: { 1: 'partly-cloudy-day-rain',       0: 'partly-cloudy-night-rain' },
  63: { 1: 'rain',                         0: 'rain' },
  65: { 1: 'overcast-rain',                0: 'overcast-rain' },
  71: { 1: 'partly-cloudy-day-snow',       0: 'partly-cloudy-night-snow' },
  73: { 1: 'snow',                         0: 'snow' },
  75: { 1: 'overcast-snow',                0: 'overcast-snow' },
  77: { 1: 'overcast-snow',                0: 'overcast-snow' },
  80: { 1: 'partly-cloudy-day-rain',       0: 'partly-cloudy-night-rain' },
  81: { 1: 'overcast-day-rain',            0: 'overcast-night-rain' },
  82: { 1: 'extreme-day-rain',             0: 'extreme-night-rain' },
  85: { 1: 'partly-cloudy-day-snow',       0: 'partly-cloudy-night-snow' },
  86: { 1: 'extreme-day-snow',             0: 'extreme-night-snow' },
  95: { 1: 'thunderstorms-day-rain',       0: 'thunderstorms-night-rain' },
  96: { 1: 'thunderstorms-day-hail',       0: 'thunderstorms-night-hail' },
  99: { 1: 'thunderstorms-overcast-day',   0: 'thunderstorms-overcast-night' },
}

export const WEATHER_CODE_GROUPS: Record<WeatherGroup, WeatherCode[]> = {
  'Clear sky':    [0],
  'Mainly clear': [1],
  'Partly cloudy':[2],
  'Overcast':     [3],
  'Fog':          [45, 48],
  'Drizzle':      [51, 53, 55],
  'Rain':         [61, 63, 65],
  'Snow':         [71, 73, 75, 77],
  'Showers':      [80, 81, 82, 85, 86],
  'Thunderstorm': [95, 96, 99],
}