import type { WeatherCode, WeatherGroup } from '@/types/weather'

export const WEATHER_CODE_MAP: Record<WeatherCode, { label: string; icon: string }> = {
  0:  { label: 'Clear sky',                    icon: 'clear-day' },
  1:  { label: 'Mainly clear',                 icon: 'clear-day' },
  2:  { label: 'Partly cloudy',                icon: 'partly-cloudy-day' },
  3:  { label: 'Overcast',                     icon: 'overcast' },
  45: { label: 'Fog',                          icon: 'fog' },
  48: { label: 'Rime fog',                     icon: 'fog' },
  51: { label: 'Light drizzle',                icon: 'drizzle' },
  53: { label: 'Moderate drizzle',             icon: 'drizzle' },
  55: { label: 'Dense drizzle',                icon: 'overcast-drizzle' },
  61: { label: 'Slight rain',                  icon: 'rain' },
  63: { label: 'Moderate rain',                icon: 'rain' },
  65: { label: 'Heavy rain',                   icon: 'overcast-rain' },
  71: { label: 'Slight snow',                  icon: 'snow' },
  73: { label: 'Moderate snow',                icon: 'snow' },
  75: { label: 'Heavy snow',                   icon: 'overcast-snow' },
  77: { label: 'Snow grains',                  icon: 'overcast-snow' },
  80: { label: 'Slight rain showers',          icon: 'rain' },
  81: { label: 'Moderate rain showers',        icon: 'overcast-rain' },
  82: { label: 'Violent rain showers',         icon: 'overcast-rain' },
  85: { label: 'Slight snow showers',          icon: 'snow' },
  86: { label: 'Heavy snow showers',           icon: 'overcast-snow' },
  95: { label: 'Thunderstorm',                 icon: 'thunderstorms-rain' },
  96: { label: 'Thunderstorm with slight hail',icon: 'thunderstorms-overcast-rain' },
  99: { label: 'Thunderstorm with heavy hail', icon: 'thunderstorms-overcast' },
}

export const WEATHER_CODE_GROUPS: Record<WeatherGroup, WeatherCode[]> = {
  'Clear sky':    [0],
  'Mainly clear': [1],
  'Partly cloudy':[2],
  'Overcast':     [3],
  'Fog':          [45, 48],
  'Drizzle':      [51, 53, 55],
  'Rain':         [61, 63, 65],
  'Snow':         [71, 73, 75, 77],
  'Showers':      [80, 81, 82, 85, 86],
  'Thunderstorm': [95, 96, 99],
}
